// scheduler-4.0.8-trial/examples/angular/recurring-events/src/app/app.component.ts
import { Component } from '@angular/core';
import { schedulerConfig } from './schedulerConfig';

// Bryntum umd lite bundle comes without polyfills to support Angular's zone.js
import { SchedulerConfig } from 'bryntum-scheduler/scheduler.lite.umd.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  schedulerConfig: Partial<SchedulerConfig> = schedulerConfig;
}

<!--
 * App template
-->
<header>
  <h1><a id="title" href="../../../../#example-angular-recurring-events">Angular Recurring Events demo</a></h1>

  <!-- fullscreen button -->
  <bry-fullscreen></bry-fullscreen>
</header>

<bry-scheduler
  #scheduler
  [rowHeight]             = "schedulerConfig.rowHeight"
  [sortFeature]           = "schedulerConfig.features.sort"
  [eventTooltipFeature]   = "schedulerConfig.features.eventTooltip"
  [enableRecurringEvents] = "schedulerConfig.enableRecurringEvents"
  [labelsFeature]         = "schedulerConfig.features.labels"
  [columns]               = "schedulerConfig.columns"
  [crudManager]           = "schedulerConfig.crudManager"
  [startDate]             = "schedulerConfig.startDate"
  [endDate]               = "schedulerConfig.endDate"
  [viewPreset]            = "schedulerConfig.viewPreset"
  [eventRenderer]         = "schedulerConfig.eventRenderer"
  [resourceImagePath]     = "schedulerConfig.resourceImagePath"
></bry-scheduler>

// scheduler-4.0.8-trial/examples/react/typescript/recurring-events/src/App.tsx
/**
 * Main App file
 */
import React from 'react';

// our libraries
import { BryntumScheduler } from 'bryntum-react-shared';
// we import scheduler.umd for IE11 compatibility only. If you don't use IE import:

// global css
import 'bryntum-scheduler/scheduler.stockholm.css';
import 'bryntum-react-shared/resources/shared.scss';

// application scss
import './App.scss';

// application files
import Header from './Header';
import { schedulerConfig } from './schedulerConfig';

const App: React.FC = () => {

    return (
        <React.Fragment>
            <Header />
            <BryntumScheduler
                rowHeight              = {schedulerConfig.rowHeight}
                sortFeature            = {schedulerConfig.features.sort}
                eventTooltipFeature    = {schedulerConfig.features.eventTooltip}
                enableRecurringEvents  = {schedulerConfig.enableRecurringEvents}
                labelsFeature          = {schedulerConfig.features.labels}
                columns                = {schedulerConfig.columnLines}
                crudManager            = {schedulerConfig.crudManager}
                startDate              = {schedulerConfig.startDate}
                endDate                = {schedulerConfig.endDate}
                viewPreset             = {schedulerConfig.viewPreset}
                eventRenderer          = {schedulerConfig.eventRenderer}
            />
        </React.Fragment>
    );
}

export default App;
