// scheduler-4.0.8-trial/examples/vue/javascript/animations/src/App.vue
<!--
/**
 * Application implementation
 */
 -->
<template>
    <div id="app">
        <demo-header
            title="Vue Animations demo"
            link='../../../../#example-vue-javascript-animations'
        >
        <div> And here is the demo header content</div>
        </demo-header>

        <scheduler
            ref                  = "scheduler"
            :eventColor          = "schedulerConfig.eventColor"
            :columns             = "schedulerConfig.columns"
            :minHeight           = "schedulerConfig.minHeight"
            :startDate           = "schedulerConfig.startDate"
            :endDate             = "schedulerConfig.endDate"
            :viewPreset          = "schedulerConfig.viewPreset"
            :rowHeight           = "schedulerConfig.rowHeight"
            :barMargin           = "schedulerConfig.barMargin"
            :crudManager         = "schedulerConfig.crudManager"
            :useInitialAnimation = "schedulerConfig.useInitialAnimation"
            :timeRangesFeature   = "schedulerConfig.timeRangesFeature"
            :resourceImagePath   = "schedulerConfig.resourceImagePath"
        ></scheduler>
    </div>
</template>

<script>
    // header
    import DemoHeader from './components/Header.vue';

    // scheduler and its config
    import Scheduler from 'bryntum-vue-shared/src/Scheduler.vue';
    import { DateHelper } from 'bryntum-scheduler';
    import schedulerConfig from './components/schedulerConfig.js';

    // event bus
    import { eventBus } from './main';

    // we need to import it here because it comes from the package
    import 'bryntum-scheduler/scheduler.stockholm.css';

    // App
    export default {
        name: 'app',

        // local components
        components: {
            DemoHeader,
            Scheduler
        },

        // function that returns data
        data() {
            return {
                schedulerConfig
            }
        }, // eo function data

        // runs after the instance is created - installs listeners
        created() {
            // centralized button click listeners
            eventBus.$on('click', this.dispatchClick);

            // slider change event listener
            eventBus.$on('duration', this.onDurationChange);
        }, // eo function created

        mounted() {

            // set the default animation duration
            this.onDurationChange(600);

        }, // eo function mounted

        methods : {
            // dispatch button clicks from this centralized
            // click handler to the respective action handlers
            dispatchClick(action) {
                const method = `${action}Handler`,
                      me = this
                ;
                // console.log(method);
                if(me[method]) me[method](action);
            }, // eo function dispatchClick

            // set time of all Meetings to max 1 hour
            maxHandler(action) {
                this.$refs.scheduler.schedulerInstance.eventStore.query((task) => task.eventType === 'Meeting').forEach((task) => task.duration = Math.min(task.duration, 1));
            }, // eo function maxHandler

            // moves events of type "Meeting" after lunch
            moveHandler(action) {
                const scheduler = this.$refs.scheduler.schedulerInstance,
                      eventStore = scheduler.eventStore
                ;
                if(scheduler.features) {
                    const lunchFinishTime = scheduler.features.timeRanges.store.getById('lunch').endDate
                    eventStore.query((task) => task.eventType === 'Meeting').forEach((task) => task.startDate = DateHelper.max(task.startDate, lunchFinishTime));
                }

            }, // eo function moveHandler

            // randomizes the events
            randomHandler(action) {
                const scheduler = this.$refs.scheduler.schedulerInstance,
                      eventStore = scheduler.eventStore,
                      indices = [],
                      nbrToAnimate = Math.min(eventStore.count, 4)
                ;

                // Grab a bunch of random events to change
                while (indices.length < nbrToAnimate) {
                    const index = Math.floor(Math.random() * eventStore.count);

                    if (!indices.includes(index)) {
                        indices.push(index);
                    }
                }
                indices.forEach((index) => {
                    const ev = eventStore.getAt(index);

                    if (ev) {
                        ev.beginBatch();
                        ev.resourceId = (scheduler.resourceStore.indexOf(ev.resource) + 2) % 8 + 1;
                        ev.setStartDate(DateHelper.add(ev.startDate, ev.startDate.getHours() % 2 ? 1 : -1, 'hour'), true);
                        ev.endBatch();
                    }
                });
            }, // eo function randomHandler

            // handle animation duration change
            onDurationChange(value) {
                const scheduler = this.$refs.scheduler.schedulerInstance;
                let styleNode = this.styleNode;

                if(!styleNode) {
                    styleNode = this.styleNode = document.createElement('style');
                    document.head.appendChild(styleNode);
                }

                scheduler.transitionDuration = value;
                styleNode.innerHTML = `.b-grid-row,.b-sch-event-wrap { transition-duration: ${value / 1000}s !important; }`;

            } // eo function onDurationChange

        }, // eo methods

        // cleanup before destroy
        beforeDestroy() {
            // remove event listeners from eventBus
            eventBus.$off['click', 'duration'];
        } // eo function beforeDestroy

    } // eo export App

</script>

<style lang="scss">
    @import './App.scss';
</style>

<!-- eof -->

// scheduler-4.0.8-trial/examples/angular/animations/src/app/app.component.ts
/**
 * App component script
 */
import { Component, ViewChild, OnInit, AfterViewInit } from '@angular/core';
import schedulerConfig from './schedulerConfig';
import { SchedulerComponent } from 'bryntum-angular-shared';

// Bryntum umd lite bundle comes without polyfills to support Angular's zone.js
import { Menu, DateHelper } from 'bryntum-scheduler/scheduler.lite.umd.js';
import TaskModel from './lib/TaskModel';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})

export class AppComponent implements OnInit, AfterViewInit {

    public schedulerConfig = schedulerConfig;
    private styleNode: HTMLStyleElement = document.createElement('style');

    @ViewChild('scheduler', { static:true }) scheduler: SchedulerComponent;

    /**
     * Runs after the view (including the child scheduler) is initializes
     */
    ngAfterViewInit() {
        this.setAnimationDuration(600);
    }

    /**
     * Runs on this component initialization
     */
    ngOnInit() {
        document.head.appendChild(this.styleNode);
    }

    /**
     * Sets the duration of animation.
     */
    setAnimationDuration(value: number) {
        this.scheduler.schedulerInstance.transitionDuration = value;
        this.styleNode.innerHTML = `.b-grid-row,.b-sch-event-wrap { transition-duration: ${value / 1000}s !important; }`;
    }

    /**
     * Initial animation button click handler
     */
    onInitialAnimation = ({ source }) => {
        const scheduler = this.scheduler.schedulerInstance;

        function play(animation: any) {
            scheduler.restartInitialAnimation(animation);
        }

        const menu = new Menu({
            forElement  : source.element,
            closeAction : 'destroy',
            width       : source.element.offsetWidth,
            items       : [
                {
                    text     : 'Fade in',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'fade-in',
                    onItem   : () => play('fade-in')
                },
                {
                    text     : 'Slide from left',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'slide-from-left',
                    onItem   : () => play('slide-from-left')
                },
                {
                    text     : 'Slide from top',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'slide-from-top',
                    onItem   : () => play('slide-from-top')
                },
                {
                    text     : 'Zoom in',
                    icon     : 'b-fa b-fa-play',
                    disabled : scheduler.useInitialAnimation === 'zoom-in',
                    onItem   : () => play('zoom-in')
                },
                {
                    text     : 'Custom',
                    icon     : 'b-fa b-fa-play',
                    cls      : 'b-separator',
                    disabled : scheduler.useInitialAnimation === 'custom',
                    onItem   : () => play('custom')
                }
            ],
            listeners   : {
                destroy() {
                    source.pressed = false;
                }
            }
        });
    }

    /**
     * Random update button click handler
     */
    onRandomUpdate = ({ source : button }) => {
        const
            scheduler = this.scheduler.schedulerInstance,
            eventStore = scheduler.eventStore,
            indices = [],
            nbrToAnimate = Math.min(eventStore.count, 4);

        // Grab a bunch of random events to change
        while (indices.length < nbrToAnimate) {
            const index = Math.floor(Math.random() * eventStore.count);

            if (!indices.includes(index)) {
                indices.push(index);
            }
        }
        indices.forEach((index) => {
            const ev: any = eventStore.getAt(index);

            if (ev) {
                ev.beginBatch();
                ev.resourceId = (scheduler.resourceStore.indexOf(ev.resource) + 2) % 8 + 1;
                ev.setStartDate(DateHelper.add(ev.startDate, ev.startDate.getHours() % 2 ? 1 : -1, 'hour'), true);
                ev.endBatch();
            }
        });

    }

    /**
     * After lunch button click handler. Moves all meetings after lunch.
     */
    onAfterLunch = () => {
        const
            scheduler = this.scheduler.schedulerInstance,
            eventStore = scheduler.eventStore,
            lunchFinishTime = scheduler.features.timeRanges.store.getById('lunch').endDate;

        eventStore.query((task: TaskModel) => task.eventType === 'Meeting')
            .forEach((task: TaskModel) => task.startDate = DateHelper.max(task.startDate as Date, lunchFinishTime));

    }

    /**
     * Max 1 hr button click handler. Resizes all Meeting to be max 1 hr long.
     */
    onMaxHour = () => {
        const scheduler = this.scheduler.schedulerInstance;
        scheduler.eventStore.query((task: TaskModel) => task.eventType === 'Meeting')
            .forEach((task: TaskModel) => task.duration = Math.min(task.duration, 1));
    }

    /**
     * Duration slider change handler
     */
    onDurationChange = ({ source : slider }) => {
        this.setAnimationDuration(slider.value);
    }

}



<!--
 *- App component template
 -->
<header>
    <h1><a id="title" href="../../../../#example-angular-animations">Angular Animations demo</a></h1>

    <bry-slider
        text          = "Animation duration"
        [max]         = 3000
        [min]         = 0
        [showTooltip] = true
        [showValue]   = false
        [step]        = 200
        [value]       = 600
        [onChange]    = "onDurationChange"
    ></bry-slider>

    <bry-button
        text       = "Max 1hr"
        [onAction] = "onMaxHour"
    ></bry-button>

    <bry-button
        text       = "After lunch"
        [onAction] = "onAfterLunch"
    ></bry-button>

    <bry-button
        text       = "Random update"
        [onAction] = "onRandomUpdate"
    ></bry-button>

    <bry-button
        text       = "Initial animation"
        icon       = "b-fa b-fa-sliders-h"
        toggleable = "true"
        [onAction] = "onInitialAnimation"
    ></bry-button>
    <bry-fullscreen></bry-fullscreen>
</header>

<bry-scheduler
    #scheduler
    [barMargin]           = "schedulerConfig.barMargin"
    [columns]             = "schedulerConfig.columns"
    [crudManager]         = "schedulerConfig.crudManager"
    [endDate]             = "schedulerConfig.endDate"
    [eventColor]          = "schedulerConfig.eventColor"
    [minHeight]           = "schedulerConfig.minHeight"
    [rowHeight]           = "schedulerConfig.rowHeight"
    [startDate]           = "schedulerConfig.startDate"
    [timeRangesFeature]   = "schedulerConfig.timeRangesFeature"
    [useInitialAnimation] = "schedulerConfig.useInitialAnimation"
    [viewPreset]          = "schedulerConfig.viewPreset"
    [resourceImagePath]   = "schedulerConfig.resourceImagePath"
></bry-scheduler>
