// scheduler-4.0.8-trial/examples/angular/angular-4/src/app/scheduler/scheduler.component.ts
/*!
 *
 * Bryntum Scheduler 4.0.8 (TRIAL VERSION)
 *
 * Copyright(c) 2021 Bryntum AB
 * https://bryntum.com/contact
 * https://bryntum.com/license
 *
 */
import { Component, OnInit, OnChanges, ElementRef, Input, Output, EventEmitter, SimpleChanges } from '@angular/core';

declare var bryntum: any;

@Component({
    selector : 'scheduler',
    template : '<div></div>'
})
export class SchedulerComponent implements OnInit, OnChanges {

    private elementRef: ElementRef;
    private schedulerInstance: any;

    // Available features
    private featureInputs = [
        'cellEdit',
        'cellMenu',
        'cellTooltip',
        'columnLines',
        'columnPicker',
        'columnReorder',
        'columnResize',
        'dependencies',
        'eventDrag',
        'eventDragCreate',
        'eventEdit',
        'eventFilter',
        'eventMenu',
        'eventResize',
        'eventTooltip',
        'filter',
        'filterBar',
        'group',
        'groupSummary',
        'headerMenu',
        'labels',
        'nonWorkingTime',
        'regionResize',
        'scheduleTooltip',
        'search',
        'sort',
        'stripe',
        'summary',
        'timeAxisHeaderMenu',
        'timeRanges',
        'tree'
    ];

    // Available configs
    private configInputs = [
        'autoHeight',
        'eventBodyTemplate',
        'eventStore',
        'resources',
        'assignmentStore',
        'barMargin',
        'columns',
        'crudManager',
        'dependencyStore',
        'emptyText',
        'endDate',
        'eventColor',
        'eventLayout',
        'eventRenderer',
        'events',
        'eventStyle',
        'height',
        'minHeight',
        'minWidth',
        'readOnly',
        'resourceImagePath',
        'resourceStore',
        'responsiveLevels',
        'rowHeight',
        'startDate',
        'viewPreset',
        'width'
    ];

    // Configs
    @Input() autoHeight: boolean = false;
    @Input() barMargin: number = 5;
    @Input() columns: object[];
    @Input() emptyText: string;
    @Input() endDate: any;
    @Input() events: object[];
    @Input() eventColor: string;
    @Input() eventLayout: string;
    @Input() eventStyle: string;
    @Input() eventRenderer: any;
    @Input() height: number | string;
    @Input() minHeight: number | string;
    @Input() minWidth: number | string;
    @Input() resourceImagePath: string;
    @Input() resources: object[];
    @Input() readOnly: boolean = false;
    @Input() responsiveLevels: any;
    @Input() rowHeight: number = 50;
    @Input() startDate: any;
    @Input() viewPreset: string = 'hourAndDay';
    @Input() width: number | string;

    // Features, only used for initialization
    @Input() cellEdit: boolean | object = true;
    @Input() cellMenu: boolean | object = true;
    @Input() columnLines: boolean | object = true;
    @Input() dependencies: boolean | object = false;
    @Input() eventDrag: boolean | object = true;
    @Input() eventDragCreate: boolean | object = true;
    @Input() eventEdit: boolean | object = true;
    @Input() eventFilter: boolean | object = true;
    @Input() eventMenu: boolean | object = true;
    @Input() eventResize: boolean | object = true;
    @Input() eventTooltip: boolean | object = true;
    @Input() group: boolean | object | string = true;
    @Input() groupSummary: boolean | object;
    @Input() headerMenu: boolean | object = true;
    @Input() labels: boolean | object;
    @Input() nonWorkingTime: boolean;
    @Input() scheduleTooltip: boolean | object = true;
    @Input() sort: boolean | object | string = true;
    @Input() stripe: boolean;
    @Input() summary: boolean | object;
    @Input() timeAxisHeaderMenu: boolean | object;
    @Input() timeRanges: boolean | object[] = true;

    @Output() selectedEvent: string = '';
    @Output() onSchedulerEvents = new EventEmitter<object>();

    constructor(element: ElementRef) {
        // Needed later, used as target when rendering Bryntum Grid
        this.elementRef = element;
    }

    ngOnInit() {
        const
            // Features config object
            featureConfig = {},
            // Grid config object
            config = {
                // Render scheduler to components element
                appendTo : this.elementRef.nativeElement.firstElementChild,

                // Listeners, will relay events
                listeners : {
                    catchAll(event) {
                        if (event.type === 'eventselectionchange') {
                            this.selectedEvent = event.selected.length ? event.selected[0].name : '';
                        }

                        this.onSchedulerEvents.emit(event);
                    },

                    thisObj : this
                },

                features : featureConfig
            };

        // Pass configs on to scheduler
        this.configInputs.forEach(configName => {
            if (configName in this) {
                config[configName] = this[configName];
            }
        });

        // Pass feature configs on to scheduler
        this.featureInputs.forEach(featureName => {
            if (featureName in this) {
                featureConfig[featureName] = this[featureName];
            }
        });

    const engine = this.schedulerInstance = new bryntum.scheduler.Scheduler(config);

        // Relay events from eventStore and resourceStore, making them a bit easier to catch in your app
        engine.eventStore.relayAll(engine, 'events');
        engine.resourceStore.relayAll(engine, 'resources');
    }

    ngOnChanges(changes: SimpleChanges) {

        let me = this;

    if (me.schedulerInstance) {
            // Iterate over all changes
            Object.entries(changes).forEach(([name, { currentValue }]) => {
                // Apply changes that match configs to grid
                if (me.configInputs.includes(name)) {
          me.schedulerInstance[name] = currentValue;
                }

                if (me.featureInputs.includes(name)) {
          me.schedulerInstance[name] = currentValue;
                }
            })
        }
    }

    removeEvent() {
    const scheduler = this.schedulerInstance;
        scheduler.eventStore.remove(scheduler.selectedEvents);
        this.selectedEvent = '';
    }

    addEvent() {
    const scheduler = this.schedulerInstance,
            startDate = new Date(scheduler.startDate.getTime()),
            endDate = new Date(startDate.getTime());

        endDate.setHours(endDate.getHours() + 1);

        scheduler.eventStore.add({
            resourceId : scheduler.resourceStore.first.id,
            startDate  : startDate,
            endDate    : endDate,
            name       : 'New task',
            eventType  : 'Meeting'
        })
    }
}

// scheduler-4.0.8-trial/examples/vue/typescript/wrappers/Scheduler.vue
<template>
    <div class="scheduler-container"></div>
</template>

<script lang="ts">
    import { Component, Vue } from "vue-property-decorator";
    import { Scheduler } from "bryntum-scheduler";

    // Defines a Vue component that wraps Bryntum Scheduler
    @Component({
        props : {
            // Configs
            autoHeight                     : Boolean,
            barMargin                      : Number,
            columns                        : Array,
            emptyText                      : String,
            eventBodyTemplate              : Function,
            eventColor                     : String,
            eventLayout                    : String,
            eventRenderer                  : Function,
            eventStyle                     : String,
            endDate                        : Date,
            fillTicks                      : Boolean,
            forceFit                       : Boolean,
            hideHeaders                    : Boolean,
            id                             : String,
            milestoneCharWidth             : Number,
            milestoneLayoutMode            : String,
            multiEventSelect               : Boolean,
            readOnly                       : Boolean,
            responsiveLevels               : {
                default : undefined,
                type    : Object
            },
            rowHeight                      : Number,
            startDate                      : Date,
            viewPreset                     : {
                default : "hourAndDay",
                type    : [ String, Object ]
            },

            // Stores
            assignmentStore : Object,
            dependencyStore : Object,
            eventStore      : Object,
            resourceStore   : Object,
            equipmentStore  : Object,

            crudManager : Object,

            // Data
            assignments  : Array,
            dependencies : Array,
            events       : Array,
            resources    : Array,
            timeRanges   : Array,

            config : Object,

            // Features, only used for initialization
            cellEditFeature           : { type : [Boolean, Object], default : true },
            cellMenuFeature           : { type : [Boolean, Object], default : true },
            columnLinesFeature        : { type : Boolean, default : true },
            dependenciesFeature       : [Boolean, Object],
            eventMenuFeature          : { type : [Boolean, Object], default : true },
            eventDragCreateFeature    : { type : [Boolean, Object], default : true },
            eventDragFeature          : { type : [Boolean, Object], default : true },
            eventEditFeature          : { type : [Boolean, Object], default : true },
            eventFilterFeature        : { type : [Boolean, Object], default : true },
            eventResizeFeature        : { type : [Boolean, Object], default : true },
            eventTooltipFeature       : { type : [Boolean, Object], default : true },
            groupFeature              : [Boolean, Object, String],
            groupSummaryFeature       : [Boolean, Object],
            timeAxisHeaderMenuFeature : { type : [Boolean, Object], default : true },
            labelsFeature             : [Boolean, Object],
            nonWorkingTimeFeature     : [Boolean, Object],
            regionResizeFeature       : Boolean,
            scheduleTooltipFeature    : { type : [Boolean, Object], default : true },
            sortFeature               : [Boolean, Object, String, Array],
            stripeFeature             : Boolean,
            summaryToolbarFeature     : [Boolean, Object],
            timeRangesFeature         : { type : [Boolean, Object], default : true }
        }
    })
    export default class SchedulerComponent extends Vue {
        public name = "scheduler";

        public schedulerInstance!: Scheduler;

        public mounted() {
            const propKeys = Object.keys(this.$props);
            const featureConfig: Record<string, any> = {};

            const config: Record<string, any> = {
                // Render grid to components element
                appendTo : this.$el,

                // Listeners, will relay events using $emit
                listeners : {
                    catchAll(event: any) {
                        // Uncomment this line to log events being emitted to console
                        this.$emit(event.type, event);
                    },

                    thisObj : this
                },

                features : featureConfig
            };

            // Apply all props to grid config
            propKeys.forEach((prop: any) => {
                if (prop.indexOf("Feature") > -1) {
                    const featureName = prop.substr(0, prop.length - "Feature".length);
                    // Prop is a feature config
                    featureConfig[featureName] = this.$props[prop];
                } else if (prop === "config") {
                    // Prop is a config object
                    Object.assign(config, this.$props[prop]);
                } else {
                    // Prop is a config
                    if (this.$props[prop] !== undefined) config[prop] = this.$props[prop];

                    // Set up a watcher
                    this.$watch(prop, (newValue: any) => {
                        // @ts-ignore
                        this.schedulerInstance[prop] = Array.isArray(newValue) ? newValue.slice() : newValue;
                    });
                }
            }, this);

            // Create a Bryntum Scheduler with props as configs
            this.schedulerInstance = new Scheduler(config);
        }

        public beforeDestroy() {
            // Make sure Bryntum Grid is destroyed when vue component is
            this.schedulerInstance.destroy();
        }

        // methods : {
        public removeEvent() {
            const scheduler = this.schedulerInstance;
            scheduler.eventStore.remove(scheduler.selectedEvents);
        }

        public addEvent() {
            const scheduler = this.schedulerInstance,
                startDate = new Date(scheduler.startDate.getTime()),
                endDate = new Date(startDate.getTime());

            endDate.setHours(endDate.getHours() + 1);

            scheduler.eventStore.add({
                resourceId : scheduler.resourceStore.first.id,
                name       : "New task",
                desc       : "Meeting",
                startDate,
                endDate
            });
        }
    }
</script>
