// scheduler-4.0.8-trial/examples/vue/typescript/wrappers/Scheduler.vue
<template>
    <div class="scheduler-container"></div>
</template>

<script lang="ts">
    import { Component, Vue } from "vue-property-decorator";
    import { Scheduler } from "bryntum-scheduler";

    // Defines a Vue component that wraps Bryntum Scheduler
    @Component({
        props : {
            // Configs
            autoHeight                     : Boolean,
            barMargin                      : Number,
            columns                        : Array,
            emptyText                      : String,
            eventBodyTemplate              : Function,
            eventColor                     : String,
            eventLayout                    : String,
            eventRenderer                  : Function,
            eventStyle                     : String,
            endDate                        : Date,
            fillTicks                      : Boolean,
            forceFit                       : Boolean,
            hideHeaders                    : Boolean,
            id                             : String,
            milestoneCharWidth             : Number,
            milestoneLayoutMode            : String,
            multiEventSelect               : Boolean,
            readOnly                       : Boolean,
            responsiveLevels               : {
                default : undefined,
                type    : Object
            },
            rowHeight                      : Number,
            startDate                      : Date,
            viewPreset                     : {
                default : "hourAndDay",
                type    : [ String, Object ]
            },

            // Stores
            assignmentStore : Object,
            dependencyStore : Object,
            eventStore      : Object,
            resourceStore   : Object,
            equipmentStore  : Object,

            crudManager : Object,

            // Data
            assignments  : Array,
            dependencies : Array,
            events       : Array,
            resources    : Array,
            timeRanges   : Array,

            config : Object,

            // Features, only used for initialization
            cellEditFeature           : { type : [Boolean, Object], default : true },
            cellMenuFeature           : { type : [Boolean, Object], default : true },
            columnLinesFeature        : { type : Boolean, default : true },
            dependenciesFeature       : [Boolean, Object],
            eventMenuFeature          : { type : [Boolean, Object], default : true },
            eventDragCreateFeature    : { type : [Boolean, Object], default : true },
            eventDragFeature          : { type : [Boolean, Object], default : true },
            eventEditFeature          : { type : [Boolean, Object], default : true },
            eventFilterFeature        : { type : [Boolean, Object], default : true },
            eventResizeFeature        : { type : [Boolean, Object], default : true },
            eventTooltipFeature       : { type : [Boolean, Object], default : true },
            groupFeature              : [Boolean, Object, String],
            groupSummaryFeature       : [Boolean, Object],
            timeAxisHeaderMenuFeature : { type : [Boolean, Object], default : true },
            labelsFeature             : [Boolean, Object],
            nonWorkingTimeFeature     : [Boolean, Object],
            regionResizeFeature       : Boolean,
            scheduleTooltipFeature    : { type : [Boolean, Object], default : true },
            sortFeature               : [Boolean, Object, String, Array],
            stripeFeature             : Boolean,
            summaryToolbarFeature     : [Boolean, Object],
            timeRangesFeature         : { type : [Boolean, Object], default : true }
        }
    })
    export default class SchedulerComponent extends Vue {
        public name = "scheduler";

        public schedulerInstance!: Scheduler;

        public mounted() {
            const propKeys = Object.keys(this.$props);
            const featureConfig: Record<string, any> = {};

            const config: Record<string, any> = {
                // Render grid to components element
                appendTo : this.$el,

                // Listeners, will relay events using $emit
                listeners : {
                    catchAll(event: any) {
                        // Uncomment this line to log events being emitted to console
                        this.$emit(event.type, event);
                    },

                    thisObj : this
                },

                features : featureConfig
            };

            // Apply all props to grid config
            propKeys.forEach((prop: any) => {
                if (prop.indexOf("Feature") > -1) {
                    const featureName = prop.substr(0, prop.length - "Feature".length);
                    // Prop is a feature config
                    featureConfig[featureName] = this.$props[prop];
                } else if (prop === "config") {
                    // Prop is a config object
                    Object.assign(config, this.$props[prop]);
                } else {
                    // Prop is a config
                    if (this.$props[prop] !== undefined) config[prop] = this.$props[prop];

                    // Set up a watcher
                    this.$watch(prop, (newValue: any) => {
                        // @ts-ignore
                        this.schedulerInstance[prop] = Array.isArray(newValue) ? newValue.slice() : newValue;
                    });
                }
            }, this);

            // Create a Bryntum Scheduler with props as configs
            this.schedulerInstance = new Scheduler(config);
        }

        public beforeDestroy() {
            // Make sure Bryntum Grid is destroyed when vue component is
            this.schedulerInstance.destroy();
        }

        // methods : {
        public removeEvent() {
            const scheduler = this.schedulerInstance;
            scheduler.eventStore.remove(scheduler.selectedEvents);
        }

        public addEvent() {
            const scheduler = this.schedulerInstance,
                startDate = new Date(scheduler.startDate.getTime()),
                endDate = new Date(startDate.getTime());

            endDate.setHours(endDate.getHours() + 1);

            scheduler.eventStore.add({
                resourceId : scheduler.resourceStore.first.id,
                name       : "New task",
                desc       : "Meeting",
                startDate,
                endDate
            });
        }
    }
</script>

// scheduler-4.0.8-trial/examples/angular/angular-2/app/scheduler/scheduler.component.ts
/*!
 *
 * Bryntum Scheduler 4.0.8 (TRIAL VERSION)
 *
 * Copyright(c) 2021 Bryntum AB
 * https://bryntum.com/contact
 * https://bryntum.com/license
 *
 */
import {Component, OnInit, OnChanges, ElementRef, Input, Output, EventEmitter, SimpleChanges} from '@angular/core';
import {Http, HTTP_PROVIDERS} from '@angular/http';
import 'rxjs/add/operator/map';

declare var bryntum: any;

@Component({
    selector: 'scheduler',
    template: '<div></div>',
    providers: [HTTP_PROVIDERS]
})
export class SchedulerComponent implements OnInit, OnChanges {

    private elementRef: ElementRef;
    private schedulerInstance: any;

    /**
     * @deprecated in favor of schedulerInstance
     */
    public get schedulerEngine() : any {
        console.warn('schedulerEngine is deprecated. Use schedulerInstance instead.')
        return this.schedulerInstance;
    }

    // Available features
    private featureInputs = [
        'cellEdit',
        'cellMenu',
        'cellTooltip',
        'columnLines',
        'columnPicker',
        'columnReorder',
        'columnResize',
        'dependencies',
        'eventDrag',
        'eventDragCreate',
        'eventEdit',
        'eventFilter',
        'eventMenu',
        'eventResize',
        'eventTooltip',
        'filter',
        'filterBar',
        'group',
        'groupSummary',
        'headerMenu',
        'labels',
        'nonWorkingTime',
        'regionResize',
        'scheduleTooltip',
        'search',
        'sort',
        'stripe',
        'summary',
        'timeAxisHeaderMenu',
        'timeRanges',
        'tree'
    ];

    // Available configs
    private configInputs = [
        'autoHeight',
        'eventBodyTemplate',
        'eventStore',
        'resources',
        'assignmentStore',
        'barMargin',
        'columns',
        'crudManager',
        'dependencyStore',
        'emptyText',
        'endDate',
        'eventColor',
        'eventLayout',
        'eventRenderer',
        'events',
        'eventStyle',
        'height',
        'minHeight',
        'minWidth',
        'readOnly',
        'resourceStore',
        'resourceImagePath',
        'responsiveLevels',
        'rowHeight',
        'startDate',
        'viewPreset',
        'width'
    ];

    // Configs
    @Input() url: string;

    @Input() autoHeight: boolean = true;
    @Input() columns: any[];
    @Input() events: any[];
    @Input() height: number | string;
    @Input() minHeight: number | string;
    @Input() minWidth: number | string;
    @Input() resources: any[];
    @Input() readOnly: boolean = false;
    @Input() rowHeight: number = 50;
    @Input() startDate: any;
    @Input() endDate: any;
    @Input() viewPreset: string = 'hourAndDay';
    @Input() barMargin: number = 5;
    @Input() width: number | string;
    @Input() resourceImagePath: string;

    // Features, only used for initialization
    @Input() cellEdit: boolean | any = true;
    @Input() cellMenu: boolean | any = true;
    @Input() columnLines: boolean | any = true;
    @Input() dependencies: boolean | any = false;
    @Input() eventDrag: boolean | any = true;
    @Input() eventDragCreate: boolean | any = true;
    @Input() eventEditor: boolean | any = true;
    @Input() eventFilter: boolean | any = true;
    @Input() eventMenu: boolean | any = true;
    @Input() eventResize: boolean | any = true;
    @Input() eventTooltip: boolean | any = true;
    @Input() groupSummary: boolean | any;
    @Input() headerMenu: boolean | any = true;
    @Input() labels: boolean | any;
    @Input() nonWorkingTime: boolean;
    @Input() scheduleTooltip: boolean | any = true;
    @Input() summaryToolbar: boolean | any;
    @Input() timeAxisHeaderMenu: boolean | any;
    @Input() timeRanges: boolean | any[] = true;

    @Output() selectedEvent: string = '';
    @Output() onSchedulerEvents = new EventEmitter<any>();

    constructor(private http: Http, element: ElementRef) {
        // Needed later, used as target when rendering Bryntum Grid
        this.elementRef = element;
    }

    ngOnInit() {
        const
            // Features config object
            featureConfig = {},
            // Grid config object
            config = {
                // Render scheduler to components element
                appendTo: this.elementRef.nativeElement.firstElementChild,

                // Listeners, will relay events
                listeners: {
                    catchAll(event) {
                        if (event.type === 'eventselectionchange') {
                            this.selectedEvent = event.selected.length ? event.selected[0].name : '';
                        }

                        this.onSchedulerEvents.emit(event);
                    },

                    thisObj: this
                },

                features: featureConfig
            };

        // Pass configs on to scheduler
        this.configInputs.forEach(configName => {
            if (configName in this) {
                config[configName] = this[configName];
            }
        });

        // Pass feature configs on to scheduler
        this.featureInputs.forEach(featureName => {
            if (featureName in this) {
                featureConfig[featureName] = this[featureName];
            }
        });

        this.schedulerInstance = new bryntum.scheduler.Scheduler(config);

        // load data
        this.url && this.http.get(this.url)
            .map(r => r.json())
            .subscribe(
                data => this.loadData(data),
                err => console.error(err)
            );
    }

    /**
     * Consumes json in format { resources: [], events: [] }
     * @param data
     */
    loadData(data): void {
        const engine = this.schedulerInstance;
        engine.resources = data.resources.rows;
        engine.events = data.events.rows;
    }

    ngOnChanges(changes: SimpleChanges) {
        const me = this;

        if (me.schedulerInstance) {
            // Iterate over all changes
            Object.entries(changes).forEach(([name, { currentValue }]) => {
                // Apply changes that match configs to grid
                if (me.configInputs.includes(name)) {
                    me.schedulerInstance[name] = currentValue;
                }

                if (me.featureInputs.includes(name)) {
                    me.schedulerInstance[name] = currentValue;
                }
            })
        }
    }

    removeEvent() {
        const scheduler = this.schedulerInstance;
        scheduler.eventStore.remove(scheduler.selectedEvents);
        this.selectedEvent = '';
    }

    addEvent() {
        const scheduler = this.schedulerInstance,
            startDate = new Date(scheduler.startDate.getTime()),
            endDate = new Date(startDate.getTime());

        endDate.setHours(endDate.getHours() + 1);

        scheduler.eventStore.add({
            resourceId: scheduler.resourceStore.first.id,
            startDate: startDate,
            endDate: endDate,
            name: 'New task',
            eventType: 'Meeting'
        })
    }
}
