// scheduler-4.0.8-trial/examples/vue/javascript/custom-event-editor/src/components/EventEditor.vue
<!--
 * Custom event editor component
-->
<template>
    <v-dialog
        v-model="editorShown"
        width="500"
    >
        <v-card>
            <v-card-title
                class="headline grey lighten-2"
                primary-title
            >
                {{ eventName || '&nbsp;'}}
            </v-card-title>

            <v-card-text class="pt-5">
                <v-text-field
                    label="Name"
                    v-model="eventName"
                    prepend-icon="mdi-file-document-edit-outline"
                    class="pb-3"
                ></v-text-field>
                <datetime v-model="startDate" label="Start" />
                <datetime v-model="endDate" label="End" />
            </v-card-text>

            <v-divider></v-divider>

            <v-card-actions>
                <div class="flex-grow-1"></div>
                <v-btn color="primary" text @click="editorShown = false">Cancel</v-btn>
                <v-btn color="primary" text @click="saveHandler">Save</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

<script>
    import Datetime from './DateTime.vue';

    export default {
        name  : 'event-editor',

        props : {
            value : [ Boolean, Object ],
            eventRecord : Object,
            eventStore : Object,
            resourceId : [ String, Number ]
        }, // eo props

        components : {
            Datetime
        }, // eo components

        data() {
            return {
                eventName : '',
                endDate : null,
                startDate : null
            }
        }, // eo data

        methods: {
            saveHandler(){
                var me = this;

                // calling this method updates also duration (resizes the event)
                me.eventRecord.set({name: me.eventName});
                me.eventRecord.setStartEndDate(me.startDate, me.endDate);

                if(!me.eventRecord.eventStore) {
                    me.eventStore.add(me.eventRecord);
                    me.eventRecord.resourceId = me.resourceId;
                }
                // close the editor
                me.editorShown = false;
            } // eo function saveHandler
        }, // eo methods

        computed : {
            editorShown : {
                get() {
                    const
                        me = this,
                        eventRecord = me.eventRecord
                    ;

                    // we're opening so initialize data
                    if(true === me.value) {
                        if(eventRecord) {
                            Object.assign(me, {
                                eventName : eventRecord.name,
                                startDate : new Date(eventRecord.startDate),
                                endDate : new Date(eventRecord.endDate)
                            })
                        }
                    }
                    // we're closing so fire close event
                    else if(false === me.value) {
                        this.$emit('close');
                    }

                    // return always Boolean
                    return !!this.value;
                },
                // only runs on close
                set(value) {
                    this.$emit('input', value);
                }
            } // eo editorShown
        } // eo computed
    } // eo export default

</script>

<!-- eof -->

// scheduler-4.0.8-trial/examples/angular/custom-event-editor/src/app/event-editor/event-editor.component.ts
/**
 * Custom, Angular-based event editor implementation
 */
import { Component, Inject } from '@angular/core';
import {MAT_DIALOG_DATA, MatDialogRef} from "@angular/material";

@Component({
    selector    : 'custom-event-editor',
    templateUrl : './event-editor.component.html',
    styleUrls   : ['./event-editor.component.scss']
})
export class EventEditorComponent {

    name        : string;
    desc        : string;
    startDate   : Date;
    endDate     : Date;
    eventRecord : any;
    eventStore  : any;
    resourceId  : any;

    constructor(
      private dialogRef: MatDialogRef<EventEditorComponent>,
      @Inject(MAT_DIALOG_DATA) data : any
    ) {

        if(data) {
            if(data.eventRecord) {
                Object.assign(this, {
                    name        : data.eventRecord.name,
                    desc        : data.eventRecord.desc,
                    startDate   : new Date(data.eventRecord.startDate),
                    endDate     : new Date(data.eventRecord.endDate),
                    eventRecord : data.eventRecord,
                    resourceId  : data.resourceRecord.id,
                    eventStore  : data.eventStore
                });
            }
        }

    }

    save() {
        const eventRecord = this.eventRecord,
              data : any = {
                name       : this.name,
                desc       : this.desc || '',
                startDate  : this.startDate,
                endDate    : this.endDate,
                resourceId : this.resourceId,
                iconCls    : this.eventRecord.iconCls || 'b-fa b-fa-calendar'
              }
        ;
        if(!eventRecord.eventStore) {
            this.eventStore.add(eventRecord);
        }
        eventRecord.set(data);

        this.dialogRef.close();
    }

    close() {
        this.dialogRef.close();
    }

}



<!--
/**
 *- Custom, Angular-based event editor template
 */
-->
<h2 mat-dialog-title>{{name}}&nbsp;</h2>

<mat-dialog-content>

    <mat-form-field class="field-name">
        <input matInput [(ngModel)]="name" placeholder="Event name">
    </mat-form-field>

    <mat-form-field class="field-desc">
        <input matInput [(ngModel)]="desc" placeholder="Description">
    </mat-form-field>
    
    <date-time-field
        [(value)]="startDate"
        fieldLabel="Start"
    ></date-time-field>
    
    <date-time-field
        [(value)]="endDate"
        fieldLabel="End"
    ></date-time-field>

</mat-dialog-content>

<mat-dialog-actions>

    <button class="mat-raised-button"
        (click)="close()"
    >Cancel</button>

    <button class="mat-raised-button mat-primary"
        (click)="save()"
    >Save</button>

</mat-dialog-actions>


<!-- eof -->
