// scheduler-4.0.8-trial/examples/vue/javascript/custom-event-editor/src/App.vue
<!--
/**
 * Application file
 */
-->
<template>
    <v-app>
        <demo-header
            title="Vue Custom Event Editor demo"
            link='../../../../#example-vue-javascript-custom-event-editor'
        >
        </demo-header>

        <scheduler
            ref                = "scheduler"
            :columns           = "schedulerConfig.columns"
            :resources         = "schedulerConfig.resources"
            :events            = "schedulerConfig.events"
            :minHeight         = "schedulerConfig.minHeight"
            :startDate         = "schedulerConfig.startDate"
            :endDate           = "schedulerConfig.endDate"
            :viewPreset        = "schedulerConfig.viewPreset"
            :rowHeight         = "schedulerConfig.rowHeight"
            :barMargin         = "schedulerConfig.barMargin"
            :multiEventSelect  = "schedulerConfig.multiEventSelect"
            :resourceImagePath = "schedulerConfig.resourceImagePath"
            :listeners         = "listeners"
        ></scheduler>

        <event-editor
            v-model      = "showEditor"
            :eventRecord = "eventRecord"
            :eventStore  = "eventStore"
            :resourceId  = "resourceId"
            @close       = "onCloseEditor"
        ></event-editor>
    </v-app>
</template>

<script>
    // header
    import DemoHeader from './components/Header.vue';

    // event editor
    import EventEditor from './components/EventEditor.vue';

    // scheduler and its config
    import Scheduler from 'bryntum-vue-shared/src/Scheduler.vue';
    import schedulerConfig from './components/schedulerConfig.js';

    // we need to import it here because it comes from the package
    import 'bryntum-scheduler/scheduler.stockholm.css';

    // App
    export default {
        name : 'app',

        // local components
        components : {
            DemoHeader,
            Scheduler,
            EventEditor
        },

        // function that returns data
        data() {
            return {
                schedulerConfig,
                showEditor  : false,
                eventRecord : null,
                eventStore  : null,
                resourceId  : null,
                listeners   : {
                    beforeEventEdit : this.beforeEventEditHandler
                }
            }
        }, // eo function data

        methods : {
            beforeEventEditHandler(event) {
                this.openEditor(event);
                return false;
            },

            openEditor({source, resourceRecord, eventRecord}) {
                Object.assign(this, {
                    eventStore  : source.eventStore,
                    resourceId  : resourceRecord.id,
                    eventRecord : eventRecord,
                    showEditor  : true
                });
            },

            onCloseEditor() {
                const engine = this.$refs.scheduler.schedulerInstance;
                if(engine) {
                    engine.refresh();
                }
            }
        } // eo methods
    } // eo export App

</script>

<style lang="scss">
  @import './App.scss';
</style>

<!-- eof -->

// scheduler-4.0.8-trial/examples/angular/custom-event-editor/src/app/app.component.ts
/**
 * Application component
 */
import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { MatDialog, MatDialogConfig } from '@angular/material';
import { SchedulerComponent } from 'bryntum-angular-shared';
import schedulerConfig from './schedulerConfig';
import { EventEditorComponent } from './event-editor/event-editor.component';

// Bryntum umd lite bundle comes without polyfills to support Angular's zone.js

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})

export class AppComponent implements AfterViewInit {
    schedulerConfig: any = schedulerConfig;

    @ViewChild(SchedulerComponent, { static : true }) scheduler: SchedulerComponent;

    constructor(public editor: MatDialog) { }

    beforeEventEdit(event): boolean {
        const
            { eventRecord, resourceRecord, eventEdit } = event,
            editorConfig = new MatDialogConfig();

        Object.assign(editorConfig, {
            disableClose : false,
            autoFocus    : true,
            width        : '500px',
            data         : {
                eventRecord,
                resourceRecord,
                eventStore : eventEdit.eventStore
            }
        });

        // console.log('data=', editorConfig.data);
        this.editor.open(EventEditorComponent, editorConfig);

        // suppress default event editor
        return false;
    }

    ngAfterViewInit() {
        // install beforeEventEdit listener
        this.scheduler.schedulerInstance.on('beforeEventEdit', this.beforeEventEdit.bind(this));
    }

    /**
     * Custom event renderer for the scheduler
     */
    eventRenderer = ({ eventRecord }: { eventRecord: any }) => {
        return `
            <div class="info">
                <div class="name">${eventRecord.name}</div>
                <div class="desc">${eventRecord.desc}</div>
            </div>
        `;
    }

}



<!--
 *- App template
-->
<header>
    <h1><a id="title" href="../../../../#example-angular-custom-event-editor">Angular Custom Event Editor demo</a></h1>

    <!-- fullscreen button -->
    <bry-fullscreen></bry-fullscreen>
</header>

<bry-scheduler
    #scheduler
    [barMargin]         = "schedulerConfig.barMargin"
    [rowHeight]         = "schedulerConfig.rowHeight"
    [minHeight]         = "schedulerConfig.minHeight"
    [eventStyle]        = "schedulerConfig.eventStyle"
    [startDate]         = "schedulerConfig.startDate"
    [endDate]           = "schedulerConfig.endDate"
    [columns]           = "schedulerConfig.columns"
    [eventEditFeature]  = "schedulerConfig.eventEditFeature"
    [crudManager]       = "schedulerConfig.crudManager"
    [resourceImagePath] = "schedulerConfig.resourceImagePath"
    [eventRenderer]     = "eventRenderer"
></bry-scheduler>

<!-- eof -->
