// scheduler-4.0.8-trial/examples/angular/drag-between-schedulers/src/app/app.component.ts
/**
 * App component script
 */
import { Component, AfterViewInit, ViewChild } from '@angular/core';
import scheduler1Config from './scheduler1Config';
import scheduler2Config from './scheduler2Config';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    scheduler1Config = scheduler1Config;
    scheduler2Config = scheduler2Config;

    @ViewChild('scheduler1', { static: true }) scheduler1 : any;

    /**
     * Handles zoom-in click event
     * @param event
     */
    onZoomIn = ({source : button}) => {
        this.scheduler1.schedulerInstance.zoomIn();
    }

    /**
     * Handles zoom-out click event
     * @param event
     */
    onZoomOut = ({source : button}) => {
        this.scheduler1.schedulerInstance.zoomOut();
    }

}

<!--
 *- Application template
-->
<header>
    <h1><a id="title" href="../../../../#example-angular-drag-between-schedulers">Angular Drag between Schedulers demo</a></h1>

    <bry-button
        icon = "b-icon b-icon-search-plus"
        tooltip = "Zoom in"
        [onAction] = "onZoomIn"
    ></bry-button>

    <bry-button
        icon = "b-icon b-icon-search-minus"
        tooltip = "Zoom out"
        [onAction] = "onZoomOut"
    ></bry-button>

    <bry-fullscreen></bry-fullscreen>
</header>

<div class="container">
    <bry-scheduler
        #scheduler1
        [schedulerId]       = "scheduler1Config.id"
        [barMargin]         = "scheduler1Config.barMargin"
        [columns]           = "scheduler1Config.columns"
        [endDate]           = "scheduler1Config.endDate"
        [events]            = "scheduler1Config.events"
        [minHeight]         = "scheduler1Config.minHeight"
        [resources]         = "scheduler1Config.resources"
        [startDate]         = "scheduler1Config.startDate"
        [viewPreset]        = "scheduler1Config.viewPreset"
        [eventDragFeature]  = "scheduler1Config.eventDragFeature"
        [sortFeature]       = "scheduler1Config.sortFeature"
        [stripeFeature]     = "scheduler1Config.stripeFeature"
        [resourceImagePath] = "scheduler1Config.resourceImagePath"
    ></bry-scheduler>

    <bry-scheduler
        #scheduler2
        [barMargin]         = "scheduler2Config.barMargin"
        [columns]           = "scheduler2Config.columns"
        [events]            = "scheduler2Config.events"
        [minHeight]         = "scheduler2Config.minHeight"
        [partner]           = "scheduler1Config.id"
        [resources]         = "scheduler2Config.resources"
        [eventDragFeature]  = "scheduler2Config.eventDragFeature"
        [sortFeature]       = "scheduler2Config.sortFeature"
        [stripeFeature]     = "scheduler2Config.stripeFeature"
        [resourceImagePath] = "scheduler2Config.resourceImagePath"
    ></bry-scheduler>
</div>

<!-- eof -->

// scheduler-4.0.8-trial/examples/vue/javascript/drag-between-schedulers/src/App.vue
<!--
 * App component
 -->

<template>
    <div id="app">
        <demo-header
            title="Vue Drag between schedulers demo"
            link='../../../../#example-vue-javascript-drag-between-schedulers'
        ></demo-header>

        <!-- top scheduler -->
        <scheduler
            ref                = "scheduler1"
            :id                = "scheduler1Config.id"
            :minHeight         = "scheduler1Config.minHeight"
            :startDate         = "scheduler1Config.startDate"
            :endDate           = "scheduler1Config.endDate"
            :viewPreset        = "scheduler1Config.viewPreset"
            :barMargin         = "scheduler1Config.barMargin"
            :stripeFeature     = "scheduler1Config.features.stripe"
            :sortFeature       = "scheduler1Config.features.sort"
            :eventDragFeature  = "scheduler1Config.features.eventDrag"
            :columns           = "scheduler1Config.columns"
            :resources         = "scheduler1Config.resources"
            :events            = "scheduler1Config.events"
            :resourceImagePath = "scheduler1Config.resourceImagePath"
        >
        </scheduler>

        <!-- bottom scheduler -->
        <scheduler
            ref                = "scheduler2"
            :partner           = "scheduler2Config.partner"
            :id                = "scheduler2Config.id"
            :minHeight         = "scheduler2Config.minHeight"
            :barMargin         = "scheduler2Config.barMargin"
            :stripeFeature     = "scheduler2Config.features.stripe"
            :sortFeature       = "scheduler2Config.features.sort"
            :eventDragFeature  = "scheduler2Config.features.eventDrag"
            :columns           = "scheduler2Config.columns"
            :resources         = "scheduler2Config.resources"
            :events            = "scheduler2Config.events"
            :resourceImagePath = "scheduler2Config.resourceImagePath"
        >
        </scheduler>
    </div>
</template>

<script>
    // header
    import DemoHeader from './components/Header.vue';

    // scheduler and its configs
    import Scheduler from './components/Scheduler.vue';
    import scheduler1Config from './components/scheduler1Config.js';
    import scheduler2Config from './components/scheduler2Config.js';

    // we need to import it here because it comes from the package
    import 'bryntum-scheduler/scheduler.stockholm.css';

    // export App
    export default {
        name: 'app',

        // local components
        components: {
            DemoHeader,
            Scheduler
        },

        // function that returns data
        data() {
            return {
                scheduler1Config,
                scheduler2Config
            }
        }
    }
</script>

<style lang="scss">
    @import './App.scss';
</style>

<!-- eof -->
