// scheduler-4.0.8-trial/examples/angular/angular-6/src/app/app.component.ts
import {Component, ViewChild, AfterViewInit} from '@angular/core';
import {NgModel} from '@angular/forms';
import {SchedulerComponent} from './scheduler/scheduler.component';
import {HttpClient} from '@angular/common/http';

declare var window: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {

  @ViewChild(SchedulerComponent) scheduler: SchedulerComponent;

  // bind properties from the application to the scheduler component
  rowHeight         = 50;
  selectedEvent     = '';
  events            = [];
  resources         = [];
  timeRanges        = true;
  barMargin         = 10;
  startDate         = new Date(2018, 1, 7, 8);
  endDate           = new Date(2018, 1, 7, 22);
  eventColor        = 'green';
  eventStyle        = 'border';
  resourceImagePath = 'assets/users/';

  columns = [
    { type: 'resourceInfo', text: 'Staff', field: 'name' },
    {
      text: 'Type',
      field: 'role',
      width: 130,
      editor: {
        type: 'combo',
        items: ['Sales', 'Developer', 'Marketing', 'Product manager'],
        editable: false,
        pickerWidth: 140
      }
    }
  ];

  eventEdit = {
      // Add extra widgets to the event editor
      items : {
          description : {
              type  : 'text',
              name  : 'desc',
              label : 'Description'
          }
      }
  };

  eventRenderer = ({eventRecord}) => {
    return `
        <div class="info">
            <div class="name">${eventRecord.name}</div>
            <div class="desc">${eventRecord.desc}</div>
        </div>
      `;
  };

  constructor(private http: HttpClient) {
    this.getData();
  }

  ngAfterViewInit() {
    // exposing scheduling engine to be easily accessible from console
    window.scheduler = this.scheduler.schedulerInstance;

    // access the engine to reach the entire scheduler API, see API docs at /docs.
    // some small examples:
    //
    // 1. Sort resources by name
    // this.scheduler.schedulerInstance.resourceStore.sort('name');
    //
    // 2. Add a new event
    // this.scheduler.schedulerInstance.eventStore.add({ startDate : xx, endDate: xx, ... });
    //
    // 3. Change the color of the first event
    // this.scheduler.schedulerInstance.eventStore.first.eventColor = 'orange';
    //
  }

  // fetch data for the scheduler
  getData() {
    const me = this;

    me.http.get('./assets/data/data.json').subscribe(data => {
      me.resources = data['resources'].rows;
      me.events = data['events'].rows;
      me.timeRanges = data['timeRanges'].rows;
    });
  }

  onSchedulerEvents(event: any) {
    // Uncomment this to log scheduler events to console
    // if (event.type === 'eventdrop') {
    //   console.log('Drop: ', event);
    // }
    //
    // if (event.type === 'eventschange') {
    //   console.log('EventStore: ', event);
    // }
    //
    // if (event.type === 'resourceschange') {
    //   console.log('ResourceStore: ', event);
    // }
  }

  // add event button click handled here
  onAddEventClick() {
    this.scheduler.addEvent();
  }

  // remove event button click handled here
  onRemoveEventClick() {
    this.scheduler.removeEvent();
  }

}

<header>
  <h1><a id="title" href="../../../#example-angular-angular-6">Angular 6 demo</a></h1>
  <label class="sel-event">Selected event: <span>{{ scheduler.selectedEvent || 'None' }}</span></label>

  <div class="barmargin">
    <label>Bar margin</label>
    <input min="0" max="20" type="number" [value]="barMargin" (input)="barMargin = $event.target.value-0">
  </div>
  <button (click)="onAddEventClick()"><i class="b-fa b-fa-plus"></i></button>
  <button class="red" (click)="onRemoveEventClick()" [disabled]="scheduler.selectedEvent == ''"><i class="b-fa b-fa-trash"></i></button>
</header>

<div id="app">
  <scheduler
    #scheduler
    [rowHeight]         = 60
    [minHeight]         = 100
    [barMargin]         = "barMargin"
    [events]            = "events"
    [resources]         = "resources"
    [timeRanges]        = "timeRanges"
    [startDate]         = "startDate"
    [endDate]           = "endDate"
    [columns]           = "columns"
    [eventColor]        = "eventColor"
    [eventStyle]        = "eventStyle"
    [eventRenderer]     = "eventRenderer"
    [eventEdit]         = "eventEdit"
    [resourceImagePath] = "resourceImagePath"
    (onSchedulerEvents) = "onSchedulerEvents($event)"
  ></scheduler>

</div>

// scheduler-4.0.8-trial/examples/react/typescript/basic/src/App.tsx
import * as React from 'react';

import { BryntumScheduler } from 'bryntum-react-shared';
import { TimeSpan } from 'bryntum-scheduler/scheduler.umd.js';

import 'bryntum-scheduler/scheduler.stockholm.css';

export default class App extends React.Component {
    state = {
        barMargin        : 5,
        selectedEvent    : '',
        eventsVersion    : 0,
        resourcesVersion : 0,
        events           : null,
        resources        : null,
        timeRanges       : null
    };

    refs!: {
        scheduler : typeof BryntumScheduler;
    };

    handleBarMarginChange = (event: any) => {
        this.setState({ barMargin: parseInt(event.target.value) });
    };

    handleAddClick = () => {
        const scheduler = this.refs.scheduler.schedulerEngine,
              startDate = new Date(scheduler.startDate.getTime()),
              endDate   = new Date(startDate.getTime());

        endDate.setHours(endDate.getHours() + 1);

        scheduler.eventStore.add({
            resourceId : scheduler.resourceStore.first.id,
            startDate  : startDate,
            endDate    : endDate,
            name       : 'New task',
            eventType  : 'Meeting'
        });
    };

    handleRemoveClick = () => {
        const schedulerEngine = this.refs.scheduler.schedulerEngine;
        // Remove selected event from the scheduler
        schedulerEngine.selectedEvents &&
            schedulerEngine.selectedEvents[0].remove();

        this.setState({ selectedEvent: '' });
    };

    handleSelectionChange = ({ selected }: { selected: any }) => {
        this.setState({
            selectedEvent : (selected.length && selected[0].name) || ''
        });
    };

    componentDidMount() {
        fetch('data/data.json').then(response => {
            response.json().then(data => {
                this.setState({
                    // Increment these to notify BryntumScheduler that it should process events/resources
                    eventsVersion    : 1,
                    resourcesVersion : 1,

                    events     : data.events.rows,
                    resources  : data.resources.rows,
                    timeRanges : data.timeRanges.rows
                });
            });
        });
    }

    render() {
        return (
            <div className = "outer">
                <header>
                    <h1>
                        <a id="title" href="../../../../#example-react-typescript-basic">React + TypeScript basic demo</a>
                    </h1>

                    <label className = "selected-event">
                        Selected event : {' '}
                        <span>
                            {this.state.selectedEvent || 'None'}
                        </span>
                    </label>

                    <div className = "barmargin">
                        <label>Barmargin : </label>
                        <input
                            min      = "0"
                            max      = "10"
                            type     = "number"
                            value    = {this.state.barMargin}
                            onChange = {this.handleBarMarginChange}
                        />
                    </div>

                    <button onClick   = {this.handleAddClick}>
                    <i      className = "b-fa b-fa-plus" />
                    </button>
                    <button
                        disabled  = {this.state.selectedEvent === ''}
                        className = "red"
                        onClick   = {this.handleRemoveClick}
                    >
                        <i className = "b-fa b-fa-trash" />
                    </button>
                </header>

                <BryntumScheduler
                    ref = {'scheduler'}
                    // Make grid grow to fit rows
                    autoHeight = {true}
                    // Initial row height
                    barMargin        = {this.state.barMargin}
                    eventsVersion    = {this.state.eventsVersion}
                    resourcesVersion = {this.state.resourcesVersion}
                    events           = {this.state.events}
                    resources        = {this.state.resources}
                    timeRanges       = {{
                        store: {
                            modelClass : TimeSpan,
                            storeId    : 'timeRanges',
                            data       : this.state.timeRanges
                        }
                    }}
                    startDate = {new Date(2018, 1, 7, 8)}
                    endDate   = {new Date(2018, 1, 7, 22)}
                    resourceImagePath = {'users/'}
                // Columns in scheduler
                    columns={[
                        {
                            type      : 'resourceInfo',
                            text      : 'Staff',
                            showImage : true,
                            width     : 130
                        },
                        {
                            text  : 'Type',
                            field : 'role',
                            width : 130
                        }
                    ]}
                    onEventSelectionChange={
                        this.handleSelectionChange
                    }
                />
            </div>
        );
    }
}
