// scheduler-4.0.8-trial/examples/vue/javascript/dependencies/src/App.vue
<!--
/**
 * Application implementation
 */
 -->
<template>
    <div id="app">
        <demo-header
            title="Vue Dependencies demo"
            link='../../../../#example-vue-javascript-dependencies'
        ></demo-header>

        <scheduler
            ref                  = "scheduler"
            :eventColor          = "schedulerConfig.eventColor"
            :eventStyle          = "schedulerConfig.eventStyle"
            :columns             = "schedulerConfig.columns"
            :minHeight           = "schedulerConfig.minHeight"
            :startDate           = "schedulerConfig.startDate"
            :endDate             = "schedulerConfig.endDate"
            :viewPreset          = "schedulerConfig.viewPreset"
            :rowHeight           = "schedulerConfig.rowHeight"
            :barMargin           = "schedulerConfig.barMargin"
            :crudManager         = "schedulerConfig.crudManager"
            :timeRangesFeature   = "schedulerConfig.timeRangesFeature"
            :stripeFeature       = "schedulerConfig.stripeFeature"
            :dependenciesFeature = "schedulerConfig.dependenciesFeature"
            :eventDragFeature    = "schedulerConfig.eventDragFeature"
            :eventRenderer       = "schedulerConfig.eventRenderer"
            :resourceImagePath   = "schedulerConfig.resourceImagePath"
        ></scheduler>
    </div>
</template>

<script>
    // header
    import DemoHeader from './components/Header.vue';

    // scheduler and its config
    import Scheduler from 'bryntum-vue-shared/src/Scheduler.vue';
    import schedulerConfig from './components/schedulerConfig.js';

    // we need to import it here because it comes from the package
    import 'bryntum-scheduler/scheduler.stockholm.css';

    // App
    export default {
        name: 'app',

        // local components
        components: {
            DemoHeader,
            Scheduler
        },

        // function that returns data
        data() {
            return {
                schedulerConfig
            }
        } // eo function data
    } // eo export App

</script>

<style lang="scss">
    @import './App.scss';
</style>

<!-- eof -->

// scheduler-4.0.8-trial/examples/angular/pdf-export/src/app/app.component.ts
/**
 * app component script
 */
import { Component, ViewChild } from '@angular/core';
import {SchedulerComponent} from 'bryntum-angular-shared';
import schedulerConfig from './schedulerConfig';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    schedulerConfig: any = schedulerConfig;

    @ViewChild(SchedulerComponent, { static: true}) scheduler: SchedulerComponent;

    onExportClick() {
        this.scheduler.schedulerInstance.features.pdfExport.showExportDialog();
    }
}



<!--
* App component template
-->
<header>
    <h1><a id="title" href="../../../../#example-angular-pdf-export">Angular PDF Export demo</a></h1>
    <bry-button
        (click)    = "onExportClick()"
        cls        = "b-skip-test"
        color      = "b-orange b-raised"
        text       = "Export"
        style      = "margin-right: 1em"
    ></bry-button>
    <bry-fullscreen></bry-fullscreen>
</header>

<bry-scheduler
    #scheduler
    [barMargin]            = "schedulerConfig.barMargin"
    [columns]              = "schedulerConfig.columns"
    [crudManager]          = "schedulerConfig.crudManager"
    [eventColor]           = "schedulerConfig.eventColor"
    [eventRenderer]        = "schedulerConfig.eventRenderer"
    [eventStyle]           = "schedulerConfig.eventStyle"
    [minHeight]            = "schedulerConfig.minHeight"
    [rowHeight]            = "schedulerConfig.rowHeight"
    [startDate]            = "schedulerConfig.startDate"
    [endDate]              = "schedulerConfig.endDate"
    [viewPreset]           = "schedulerConfig.viewPreset"
    [resourceImagePath]    = "schedulerConfig.resourceImagePath"
    [dependenciesFeature]  = "schedulerConfig.dependenciesFeature"
    [eventDragFeature]     = "schedulerConfig.eventDragFeature"
    [stripeFeature]        = "schedulerConfig.stripeFeature"
    [timeRangesFeature]    = "schedulerConfig.timeRangesFeature"
    [pdfExportFeature]     = "schedulerConfig.pdfExportFeature"

></bry-scheduler>
