// scheduler-4.0.8-trial/examples/angular/_shared/projects/bryntum-angular-shared/src/lib/scheduler.component.ts
/*!
 *
 * Bryntum Scheduler 4.0.8 (TRIAL VERSION)
 *
 * Copyright(c) 2021 Bryntum AB
 * https://bryntum.com/contact
 * https://bryntum.com/license
 *
 */
import { Component, OnInit, OnChanges, ElementRef, Input, Output, EventEmitter, SimpleChanges, OnDestroy } from '@angular/core';

// Bryntum umd lite bundle comes without polyfills to support Angular's zone.js
import { Scheduler, AssignmentModel, AssignmentStore, EventModel, SchedulerConfig } from 'bryntum-scheduler/scheduler.lite.umd.js';

@Component({
    selector : 'bry-scheduler',
    template : ''
})
export class SchedulerComponent implements OnInit, OnChanges, OnDestroy {

    private elementRef: ElementRef;
    public schedulerInstance: Scheduler;

    /**
     * @deprecated in favor of schedulerInstance
     */
    public get schedulerEngine() : Scheduler {
        console.warn('schedulerEngine is deprecated. Use schedulerInstance instead.')
        return this.schedulerInstance;
    }

    private featureRe: RegExp = /Feature$/;

    /* #region features */
    private features: string[] = [
        'cellEditFeature',
        'cellMenuFeature',
        'cellTooltipFeature',
        'columnDragToolbarFeature',
        'columnLinesFeature',
        'columnPickerFeature',
        'columnReorderFeature',
        'columnResizeFeature',
        'dependenciesFeature',
        'dependencyEditFeature',
        'eventDragCreateFeature',
        'eventDragFeature',
        'eventDragSelectFeature',
        'eventEditFeature',
        'eventFilterFeature',
        'eventMenuFeature',
        'eventResizeFeature',
        'eventTooltipFeature',
        'filterBarFeature',
        'filterFeature',
        'groupFeature',
        'groupSummaryFeature',
        'headerMenuFeature',
        'headerZoomFeature',
        'labelsFeature',
        'nonWorkingTimeFeature',
        'panFeature',
        'pdfExportFeature',
        'quickFindFeature',
        'regionResizeFeature',
        'resourceTimeRangesFeature',
        'rowReorderFeature',
        'scheduleMenuFeature',
        'scheduleTooltipFeature',
        'searchFeature',
        'simpleEventEditFeature',
        'sortFeature',
        'stripeFeature',
        'summaryFeature',
        'timeAxisHeaderMenuFeature',
        'timeRangesFeature',
        'treeFeature'
    ];
    /* #endregion */

    /* #region configs */
    private configs: string[] = [
        'allowOverlap',
        'animateRemovingRows',
        'assignments',
        'assignmentStore',
        'autoAdjustTimeAxis',
        'autoHeight',
        'barMargin',
        'columnLines',
        'columns',
        'contextMenuTriggerEvent',
        'createEventOnDblClick',
        'crudManager',
        'defaultResourceImageName',
        'dependencyStore',
        'disableGridRowModelWarning',
        'displayDateFormat',
        'emptyText',
        'enableDeleteKey',
        'enableEventAnimations',
        'enableRecurringEvents',
        'enableTextSelection',
        'endDate',
        'endParamName',
        'eventBarTextField',
        'eventBodyTemplate',
        'eventColor',
        'eventLayout',
        'eventRenderer',
        'events',
        'eventSelectionDisabled',
        'eventStore',
        'eventStyle',
        'fillLastColumn',
        'fillTicks',
        'fullRowRefresh',
        'getRowHeight',
        'hasVisibleEvents',
        'height',
        'hideHeaders',
        'horizontalEventSorterFn',
        'loadMask',
        'longPressTime',
        'maintainSelectionOnDatasetChange',
        'managedEventSizing',
        'maxHeight',
        'maxWidth',
        'maxZoomLevel',
        'milestoneAlign',
        'milestoneCharWidth',
        'milestoneLayoutMode',
        'minHeight',
        'minWidth',
        'minZoomLevel',
        'mode',
        'multiEventSelect',
        'partner',
        'passStartEndParameters',
        'presets',
        'readOnly',
        'removeUnassignedEvent',
        'resizeToFitIncludesHeader',
        'resourceColumns',
        'resourceImagePath',
        'resourceMargin',
        'resources',
        'resourceStore',
        'resourceTimeRanges',
        'responsiveLevels',
        'rowHeight',
        'scrollLeft',
        'scrollTop',
        'selectedEvents',
        'selectionMode',
        'showDirty',
        'snap',
        'snapRelativeToEventStartDate',
        'startDate',
        'startParamName',
        'subGridConfigs',
        'tickWidth',
        'timeRanges',
        'timeResolution',
        'triggerSelectionChangeOnRemove',
        'useInitialAnimation',
        'viewportCenterDate',
        'viewPreset',
        'weekStartDay',
        'width',
        'workingTime',
        'zoomLevel',
        'zoomOnMouseWheel',
        'zoomOnTimeAxisDoubleClick',

        // schedulerId maps to id of the underlying scheduler
        'schedulerId',

        // only for examples, delete if you don't need them
        'transitionDuration'
    ];
    /* #endregion */

    /* #region Configs */
    // schedulerId translates to id for the scheduler engine
    @Input() schedulerId: string;

    @Input() allowOverlap: boolean = true;
    @Input() animateRemovingRows: boolean;
    @Input() assignments: AssignmentModel[] | object[];
    @Input() assignmentStore: AssignmentStore | object;
    @Input() autoAdjustTimeAxis: boolean = true;
    @Input() autoHeight: boolean = false;
    @Input() barMargin: number = 5;
    @Input() columnLines: boolean = true;
    @Input() columns: object[];
    @Input() contextMenuTriggerEvent: string;
    @Input() createEventOnDblClick: boolean = true;
    @Input() crudManager: object;
    @Input() defaultResourceImageName: string;
    @Input() dependencyStore: object;
    @Input() disableGridRowModelWarning: boolean = false;
    @Input() displayDateFormat: string;
    @Input() emptyText: string;
    @Input() enableDeleteKey: boolean = true;
    @Input() enableEventAnimations: boolean = true;
    @Input() enableRecurringEvents: boolean = false;
    @Input() enableTextSelection: boolean = false;
    @Input() endDate: any;
    @Input() endParamName: string;
    @Input() eventBarTextField: string = 'name';
    @Input() eventBodyTemplate: any;
    @Input() eventColor: string = 'green';
    @Input() eventLayout: string;
    @Input() eventRenderer: any;
    @Input() events: object[];
    @Input() eventSelectionDisabled: boolean = false;
    @Input() eventStore: object;
    @Input() eventStyle: string = 'plain';
    @Input() fillLastColumn: boolean = true;
    @Input() fillTicks: boolean;
    @Input() fullRowRefresh: boolean = true;
    @Input() getRowHeight: any;
    @Input() hasVisibleEvents: boolean;
    @Input() height: number | string;
    @Input() hideHeaders: boolean = false;
    @Input() horizontalEventSorterFn: any;
    @Input() loadMask: string = 'Loading...';
    @Input() longPressTime: number = 400;
    @Input() maintainSelectionOnDatasetChange: boolean = true;
    @Input() managedEventSizing: boolean = true;
    @Input() maxHeight: number | string;
    @Input() maxWidth: number | string;
    @Input() maxZoomLevel: number;
    @Input() milestoneAlign: string;
    @Input() milestoneCharWidth: number = 10;
    @Input() milestoneLayoutMode: string = 'default';
    @Input() minHeight: number | string;
    @Input() minWidth: number | string;
    @Input() minZoomLevel: number;
    @Input() mode: string;
    @Input() multiEventSelect: boolean;
    @Input() partner: any;
    @Input() passStartEndParameters: boolean;
    @Input() presets: object[];
    @Input() readOnly: boolean = false;
    @Input() removeUnassignedEvent: boolean = true;
    @Input() resizeToFitIncludesHeader: boolean = true;
    @Input() resourceColumns: any;
    @Input() resourceImagePath: string;
    @Input() resourceMargin: number;
    @Input() resources: object[];
    @Input() resourceStore: object;
    @Input() resourceTimeRanges: object;
    @Input() responsiveLevels: any;
    @Input() rowHeight: number = 50;
    @Input() scrollLeft: number;
    @Input() scrollTop: number;
    @Input() selectedEvents: EventModel[];
    @Input() selectionMode: object;
    @Input() showDirty: boolean = false;
    @Input() snap: boolean;
    @Input() snapRelativeToEventStartDate: boolean = false;
    @Input() startDate: any;
    @Input() startParamName: string;
    @Input() subGridConfigs: object;
    @Input() tickWidth: number;
    @Input() timeRanges: object | boolean;
    @Input() timeResolution: object;
    @Input() triggerSelectionChangeOnRemove: boolean = false;
    @Input() useInitialAnimation: boolean | string = true;
    @Input() viewportCenterDate: any;
    @Input() viewPreset: object | string = 'hourAndDay';
    @Input() weekStartDay: number;
    @Input() width: number | string;
    @Input() workingTime: object;
    @Input() zoomLevel: number;
    @Input() zoomOnMouseWheel: boolean = true;
    @Input() zoomOnTimeAxisDoubleClick: boolean = true;
    /* #endregion */

    /* #region Features, only used for initialization */
    @Input() cellEditFeature: boolean | object = true;
    @Input() cellMenuFeature: boolean | object;
    @Input() cellTooltipFeature: boolean | object = true;
    @Input() columnDragToolbarFeature: boolean | object = true;
    @Input() columnLinesFeature: boolean | object = true;
    @Input() columnPickerFeature: boolean = true;
    @Input() columnReorderFeature: boolean = true;
    @Input() columnResizeFeature: boolean = true;
    @Input() dependenciesFeature: boolean | object = false;
    @Input() dependencyEditFeature: boolean | object = false;
    @Input() eventDragCreateFeature: boolean | object = true;
    @Input() eventDragFeature: boolean | object = true;
    @Input() eventDragSelectFeature: boolean;
    @Input() eventEditFeature: boolean | object = true;
    @Input() eventFilterFeature: boolean | object = true;
    @Input() eventMenuFeature: boolean | object = true;
    @Input() eventResizeFeature: boolean | object = true;
    @Input() eventTooltipFeature: boolean | object = true;
    @Input() filterBarFeature: boolean | object;
    @Input() filterFeature: boolean | object;
    @Input() groupFeature: boolean | object | string = true;
    @Input() groupSummaryFeature: boolean | object;
    @Input() headerMenuFeature: boolean | object;
    @Input() headerZoomFeature: boolean;
    @Input() labelsFeature: boolean | object;
    @Input() nonWorkingTimeFeature: boolean;
    @Input() panFeature: boolean | object;
    @Input() pdfExportFeature: boolean | object;
    @Input() quickFindFeature: boolean | object;
    @Input() regionResizeFeature: boolean;
    @Input() resourceTimeRangesFeature: boolean;
    @Input() rowReorderFeature: boolean;
    @Input() scheduleMenuFeature: boolean | object = true;
    @Input() scheduleTooltipFeature: boolean | object = true;
    @Input() searchFeature: boolean;
    @Input() simpleEventEdit: boolean | object;
    @Input() sortFeature: boolean | object | string = true;
    @Input() stripeFeature: boolean;
    @Input() summaryFeature: boolean | object;
    @Input() timeAxisHeaderMenuFeature: boolean | object;
    @Input() timeRangesFeature: boolean | object[] = true;
    @Input() treeFeature: boolean;
    /* #endregion */

    // for examples only, delete
    @Input() transitionDuration: number;
    @Output() selectedEvent: string = '';
    @Output() onSchedulerEvents = new EventEmitter<object>();

    constructor(element: ElementRef) {
        // Needed later, used as target when rendering Bryntum Scheduler
        this.elementRef = element;
    }

    /**
     * Initializes component
     */
    ngOnInit() {
        const
            config = {
                // Render scheduler to components element
                appendTo : this.elementRef.nativeElement,

                // Listeners, will relay events
                listeners : {
                    catchAll(event) {
                        if (event.type === 'eventselectionchange') {
                            this.selectedEvent = event.selected.length ? event.selected[0].name : '';
                        }

                        this.onSchedulerEvents.emit(event);
                    },

                    thisObj : this
                },

                features : {}
            }
        ;

        // relay properties with names matching this.featureRe to features
        this.features.forEach(featureName => {
            if (featureName in this) {
                config.features[featureName.replace(this.featureRe, '')] = this[featureName];
            }
        });

        // Pass configs on to scheduler
        this.configs.forEach(configName => {
            if (configName in this) {
                // application may want to pass id for the engine is schedulerId
                if ('schedulerId' === configName && this[configName]) {
                    config['id'] = this[configName];
                } else {
                    config[configName] = this[configName];
                }
            }
        });

        // The application may have passed string id of the partner so
        // we attempt to find the real instance of the scheduler with that id
        if (config['partner'] && 'string' === typeof (config['partner'])) {
            const
                bryntum = window['bryntum'],
                partner = bryntum && bryntum.get && bryntum.get(config['partner']);
            config['partner'] = partner || undefined;
        }

        // The Angular 11 application when compiled for production with buildOptimizer: true
        // fails on scheduler re-creation if any of this data sets is bound in template. It may
        // have something to do with the Angular build optimization process. Assigning the
        // data after the scheduler has been created resolves the issue.
        // https://github.com/bryntum/support/issues/2157
        const stores = {};
        [
            'resources',
            'events',
            'assignments',
            'dependencies',
            'timeRanges',
            'resourceTimeRanges'
        ].forEach((name) => {
            if (config[name]) {
                stores[name] = config[name];
                delete config[name];
            }
        });

        this.schedulerInstance = new Scheduler(config);

        Object.assign(this.schedulerInstance, stores);
    }

    ngOnChanges(changes: SimpleChanges) {

        const me = this;

        if (me.schedulerInstance) {
            // Iterate over all changes
            Object.entries(changes).forEach(([name, { currentValue }]) => {
                // Apply changes that match configs to grid
                if (me.configs.includes(name)) {
                    me.schedulerInstance[name] = currentValue;
                }

                if (me.features.includes(name)) {
                    me.schedulerInstance[name.replace(this.featureRe, '')] = currentValue;
                }
            });
        }
    }

    removeEvent() {
        const scheduler = this.schedulerInstance;
        scheduler.eventStore.remove(scheduler.selectedEvents);
        this.selectedEvent = '';
    }

    addEvent() {
        const
            scheduler = this.schedulerInstance,
            event = new scheduler.eventStore.modelClass({
                resourceId   : scheduler.resourceStore.first.id,
                startDate    : scheduler.startDate,
                duration     : 1,
                durationUnit : 'h',
                name         : 'New task',
                eventType    : 'Meeting'
            }) as EventModel;

        scheduler.editEvent(event);
    }

    /**
     * Destroys component
     */
    ngOnDestroy(): void {
        if (this.schedulerInstance) {
            this.schedulerInstance.destroy();
        }
    }
}

// scheduler-4.0.8-trial/examples/vue/javascript/_shared/src/Scheduler.vue
<!--
 * Modified vue-cli/src/components/Scheduler.vue
-->
<template>
    <div class="b-scheduler-container"></div>
</template>

<script>
    import { Scheduler } from 'bryntum-scheduler';

    // Defines a Vue component that wraps Bryntum Scheduler
    export default {

        name  : 'scheduler',

        props : {
            // Configs
            allowOverlap                     : { type : Boolean, default : undefined },
            animateRemovingRows              : { type : Boolean, default : undefined },
            autoAdjustTimeAxis               : { type : Boolean, default : undefined },
            autoHeight                       : { type : Boolean, default : undefined },
            barMargin                        : { type : Number, default : 5 },
            columnLines                      : { type : Boolean, default : undefined },
            columns                          : Array,
            contextMenuTriggerEvent          : String,
            createEventOnDblClick            : { type : Boolean, default : undefined },
            defaultResourceImageName         : String,
            disableGridRowModelWarning       : { type : Boolean, default : undefined },
            displayDateFormat                : String,
            emptyText                        : String,
            enableDeleteKey                  : { type : Boolean, default : undefined },
            enableEventAnimations            : { type : Boolean, default : undefined },
            enableRecurringEvents            : { type : Boolean, default : undefined },
            enableTextSelection              : { type : Boolean, default : undefined },
            endDate                          : Date,
            endParamName                     : String,
            eventBarTextField                : { type : String, default : 'name' },
            eventBodyTemplate                : Function,
            eventColor                       : { type : String, default : 'green' },
            eventLayout                      : String,
            eventRenderer                    : Function,
            eventSelectionDisabled           : { type : Boolean, default : undefined },
            eventStyle                       : { type : String, default : 'plain' },
            fillLastColumn                   : { type : Boolean, default : undefined },
            fillTicks                        : { type : Boolean, default : undefined },
            flex                             : String,
            forceFit                         : { type : Boolean, default : undefined },
            fullRowRefresh                   : { type : Boolean, default : undefined },
            height                           : [Number, String],
            hideHeaders                      : { type : Boolean, default : undefined },
            horizontalEventSorterFn          : Function,
            id                               : String,
            listeners                        : Object,
            loadMask                         : { type : String, default : 'Loading...' },
            longPressTime                    : { type : Number, default : 400 },
            maintainSelectionOnDatasetChange : { type : Boolean, default : undefined },
            managedEventSizing               : { type : Boolean, default : undefined },
            maxHeight                        : [Number, String],
            maxWidth                         : [Number, String],
            maxZoomLevel                     : Number,
            milestoneAlign                   : String,
            milestoneCharWidth               : { type : Number, default : 10 },
            milestoneLayoutMode              : { type : String, default : 'default' },
            minHeight                        : [Number, String],
            minWidth                         : [Number, String],
            minZoomLevel                     : Number,
            mode                             : String,
            multiEventSelect                 : { type : Boolean, default : undefined },
            partner                          : [Object, String],
            passStartEndParameters           : { type : Boolean, default : undefined },
            presets                          : [Object, Array],
            readOnly                         : { type : Boolean, default : undefined },
            removeUnassignedEvent            : { type : Boolean, default : undefined },
            resizeToFitIncludesHeader        : { type : Boolean, default : undefined },
            resourceColumns                  : Object,
            resourceImagePath                : String,
            resourceMargin                   : Number,
            resourceTimeRanges               : [Object, Array],
            responsiveLevels                 : { type : Object, default : undefined },
            rowHeight                        : { type : Number, default : 50 },
            scrollLeft                       : Number,
            scrollTop                        : Number,
            selectedEvents                   : Array,
            selectionMode                    : Object,
            showDirty                        : { type : Boolean, default : undefined },
            snap                             : { type : Boolean, default : undefined },
            snapRelativeToEventStartDate     : { type : Boolean, default : undefined },
            startDate                        : Date,
            startParamName                   : String,
            subGridConfigs                   : Object,
            tickWidth                        : Number,
            timeResolution                   : Object,
            triggerSelectionChangeOnRemove   : { type : Boolean, default : undefined },
            useInitialAnimation              : { type : [Boolean, String], default : undefined },
            viewportCenterDate               : Date,
            viewPreset                       : { type : [String, Object], default : 'hourAndDay' },
            weekStartDay                     : Number,
            width                            : [Number, String],
            workingTime                      : Object,
            zoomLevel                        : Number,
            zoomOnMouseWheel                 : { type : Boolean, default : undefined },
            zoomOnTimeAxisDoubleClick        : { type : Boolean, default : undefined },
            tbar                             : { type : [ Object, Array ], default : undefined },
            bbar                             : { type : [ Object, Array ], default : undefined },

            // Stores
            assignmentStore : Object,
            dependencyStore : Object,
            eventStore      : Object,
            resourceStore   : Object,

            crudManager : Object,

            // Data
            assignments  : Array,
            dependencies : Array,
            events       : Array,
            resources    : Array,
            timeRanges   : Array,

            config : Object,

            // Features, only used for initialization
            cellEditFeature           : { type : [Boolean, Object], default : undefined },
            cellMenuFeature           : { type : [Boolean, Object], default : undefined },
            cellTooltipFeature        : { type : [Boolean, Object], default : undefined },
            columnDragToolbarFeature  : { type : [Boolean, Object], default : undefined },
            columnLinesFeature        : { type : Boolean, default : undefined },
            columnPickerFeature       : { type : [Boolean, Object], default : undefined },
            columnReorderFeature      : { type : [Boolean, Object], default : undefined },
            columnResizeFeature       : { type : [Boolean, Object], default : undefined },
            dependenciesFeature       : { type : [Boolean, Object], default : undefined },
            dependencyEditFeature     : { type : [Boolean, Object], default : undefined },
            eventDragCreateFeature    : { type : [Boolean, Object], default : undefined },
            eventDragFeature          : { type : [Boolean, Object], default : undefined },
            eventDragSelectFeature    : { type : Boolean, default : undefined },
            eventEditFeature          : { type : [Boolean, Object], default : undefined },
            eventFilterFeature        : { type : [Boolean, Object], default : undefined },
            eventMenuFeature          : { type : [Boolean, Object], default : undefined },
            eventResizeFeature        : { type : [Boolean, Object], default : undefined },
            eventTooltipFeature       : { type : [Boolean, Object], default : undefined },
            filterBarFeature          : { type : [Boolean, Object], default : undefined },
            filterFeature             : { type : [Boolean, Object], default : undefined },
            groupFeature              : { type : [Boolean, Object, String], default : undefined },
            groupSummaryFeature       : { type : [Boolean, Object], default : undefined },
            headerMenuFeature         : { type : [Boolean, Object], default : undefined },
            headerZoomFeature         : { type : Boolean, default : undefined },
            labelsFeature             : { type : [Boolean, Object], default : undefined },
            nonWorkingTimeFeature     : { type : [Boolean, Object], default : undefined },
            panFeature                : { type : [Boolean, Object], default : undefined },
            pdfExportFeature          : { type : [Boolean, Object], default : undefined },
            quickFindFeature          : { type : [Boolean, Object], default : undefined },
            regionResizeFeature       : { type : Boolean, default : undefined },
            resourceTimeRangesFeature : { type : [Boolean, Object], default : undefined },
            rowReorderFeature         : { type : Boolean, default : undefined },
            scheduleMenuFeature       : { type : [Boolean, Object], default : undefined },
            scheduleTooltipFeature    : { type : [Boolean, Object], default : undefined },
            searchFeature             : { type : [Boolean, Object], default : undefined },
            simpleEventEdit           : { type : [Boolean, Object], default : undefined },
            sortFeature               : { type : [Boolean, Object, String, Array], default : undefined },
            stripeFeature             : { type : Boolean, default : undefined },
            summaryFeature            : { type : [Boolean, Object], default : undefined },
            timeAxisHeaderMenuFeature : { type : [Boolean, Object], default : undefined },
            timeRangesFeature         : { type : [Boolean, Object], default : undefined },
            treeFeature               : { type : [Boolean, Object], default : undefined }
        }, // eo props

        computed : {
            /**
             * @deprecated in favor of schedulerInstance
             */
            schedulerEngine() {
                console.warn('schedulerEngine is deprecated. Use schedulerInstance instead.')
                return this.schedulerInstance;
            }
        },

        // runs after the component is attached to DOM (mounted)
        mounted() {
            const propKeys = Object.keys(this.$props);

            const config = {
                // Render grid to components element
                appendTo : this.$el,

                // Listeners, will relay events using $emit
                listeners : {
                    catchAll(event) {
                        // Uncomment this line to log events being emitted to console
                        //console.log(event.type);
                        this.$emit(event.type, event);
                    },

                    thisObj : this
                },

                features : {}
            };

            // Apply all props to grid config
            propKeys.forEach(prop => {
                let match;
                if ((match = prop.match(/(.*)Feature/)) && this[prop] !== undefined) {
                    // Prop which ends with Feature is a feature config
                    config.features[match[1]] = this[prop];
                }
                else if (prop === 'config') {
                    // Prop is a config object
                    Object.assign(config, this[prop]);
                }
                else {
                    // Prop is a config
                    if (this[prop] !== undefined) {
                        config[prop] = this[prop];
                    }

                    // Set up a watcher
                    this.$watch(prop, newValue => {
                        this.schedulerInstance[prop] = Array.isArray(newValue) ? newValue.slice() : newValue;
                    });
                }
            }, this);

            // console.log('config=', config, 'props=', this.$props);

            // Create a Bryntum Grid with props as configs
            this.schedulerInstance = new Scheduler(config);

        }, // eo function mounted

        // cleanup before destroy
        beforeDestroy() {
            // Make sure Bryntum Grid is destroyed when vue component is
            this.schedulerInstance.destroy();
        } // eo function beforeDestroy

    }; // eo scheduler export

</script>

<!-- eof -->
